# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    #security_tokens:
    #    - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
    #    - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    email:
        enabled: true                  # If email authentication should be enabled, default false
        sender_email: no-reply@example.com   # Sender email address
        sender_name: Laurent Fenu          # Sender name
        digits: 4                      # Number of digits in authentication code
        template: authentification/2fa_form.html.twig   # Template used to render the authentication form
        #mailer: app.custom_mailer_service